version: "3.7"

services:
  couchdb:
    container_name: couchdb
    image: couchdb
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=docker
      - COUCHDB_PASSWORD=123456  
    volumes:
      - couchdb_data:/bitnami/couchdb

volumes:
  couchdb_data:
    driver: local